### ISSUE TITLE
Background color 

### ISSUE THREAD

**Issue by matteo-daddio** [simmone/racket-simple-svg#3]
It should be possible to choose the svg background color.

**Comment by simmone** [comment]
ok, I'll add this feature to the latest version upgrade.

Btw, I think I need more days to complete this version change, I'll take
more time to complete it as fast as I can, let you know.

matteo-daddio ***@***.***> 于2024年2月4日周日 01:44写道：

**Comment by simmone** [comment]
Add a background optional keyword argument to create a background on the canvas.

```
(svg-out
  100 100
   #:background "#BBC42A"
   ...)
```

**Comment by matteo-daddio** [comment]
Very good 😉

Matteo d’Addio
________________________________
Da: Chen Xiao ***@***.***>
Inviato: Saturday, February 24, 2024 1:22:45 AM
A: simmone/racket-simple-svg ***@***.***>
Cc: matteo-daddio ***@***.***>; Author ***@***.***>
Oggetto: Re: [simmone/racket-simple-svg] Background color (Issue #3)


Add a background optional keyword argument to create a background on the canvas.

(svg-out
  100 100
   #:background "#BBC42A"
   ...)
