### ISSUE TITLE
Line arrows 

### ISSUE THREAD

**Issue by matteo-daddio** [simmone/racket-simple-svg#5]
Hi Chen,
it would be useful for me to create lines with arrows. Do you think you will add such feature?

**Comment by simmone** [comment]
Good suggestion! thank you.

I need add new word "marker" to the code.

I find this on internet, a good article about line with arrow:

[https://blog.shalvah.me/posts/learn-svg-by-drawing-an-arrow](url)

I'll need some time to understand and complete it, maybe you can use polygon to write your line with arrow first?

Thank you again.

**Comment by simmone** [comment]
Add a new shape: arrow, specify start point, end point,handle base, head base, head height to generate a arrow shape's polygon, please try it.

![arrow1_show](https://github.com/user-attachments/assets/ecc4b32d-08bf-457f-809f-5ddcc73f02db)

**Comment by matteo-daddio** [comment]
Very good Chen.
