### ISSUE TITLE
Line with arrows

### ISSUE THREAD

**Issue by matteo-daddio** [simmone/racket-simple-svg#6]
Hi Chen, your arrows are very good, but they aren't what I had in mind.

![Chen arrows](https://github.com/user-attachments/assets/4445e633-4a01-4f68-aa83-ad6ad6f3ba28)

I mean these arrows.
What do you think?

**Comment by simmone** [comment]
Get it, i think it's a marker, I'll add this feature.

matteo-daddio ***@***.***> 于2024年10月30日周三 20:14写道：

**Comment by matteo-daddio** [comment]
Great 🙂

**Comment by simmone** [comment]
Add marker shape, usage is below, please check it meet your requirement or not.

```
                    [_marker (svg-def-shape (new-marker 'triangle))]
                    [line_id (svg-def-shape (new-line '(0 . 0) '(100 . 0)))]
                    [_sstyle (sstyle-new)]
                    )

                (set-SSTYLE-stroke-width! _sstyle 5)
                (set-SSTYLE-stroke! _sstyle "#000000")
                (svg-place-widget line_id #:at '(50 . 50) #:style _sstyle #:marker_end_id _marker)

```

![marker1](https://github.com/user-attachments/assets/e6249933-f17e-4f3f-bd1e-56c82c0bf5cd)

The arrowhead is auto rotation and the size is synchronize with stroke width.

**Comment by matteo-daddio** [comment]
Great. There are different types of arrows, do you think you will add some of them in the future?
My favorite is the one I circled in yellow.

**Comment by simmone** [comment]
Of course, give me some time.

**Comment by simmone** [comment]
Added some types, your favorite should be 'curve2, please check it again.

**Comment by matteo-daddio** [comment]
Very good Chen. I think that the arrow is a bit too small compared to the line width.

**Comment by simmone** [comment]
The arrow size compared to the line width is controled by #:size,  default is 6, you can set it bigger: 

`[size8_marker (svg-def-shape (new-marker 'curve2 #:size 8))]`

I give a example in the racket docs.

You check this is ok? If not, tell me, I change the basic shape.
